# Generated by Django 6.0.3 on 2026-04-21 04:29

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auditoria'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('refunded', 'Reembolsado'), ('pending_refund', 'Reembolso Pendente')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
