# Generated by Django 5.2.13 on 2026-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_usuario_managers_alter_compra_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='unique_avaliacao',
        ),
        migrations.RemoveConstraint(
            model_name='compra',
            name='unique_compra',
        ),
        migrations.RemoveIndex(
            model_name='avaliacao',
            name='courses_ava_curso_i_3628ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='avaliacao',
            name='courses_ava_usuario_f0ca9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='avaliacao',
            name='courses_ava_curso_i_4e9b23_idx',
        ),
        migrations.RemoveIndex(
            model_name='compra',
            name='courses_com_usuario_58a219_idx',
        ),
        migrations.RemoveIndex(
            model_name='compra',
            name='courses_com_curso_i_a0a207_idx',
        ),
        migrations.RemoveIndex(
            model_name='compra',
            name='courses_com_status_08378c_idx',
        ),
        migrations.RemoveIndex(
            model_name='compra',
            name='courses_com_usuario_ef553f_idx',
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='courses_cur_nome_129570_idx',
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='courses_cur_criado__a701b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='courses_usu_criacao_435bd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='courses_usu_email_253a40_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='criacao',
        ),
        migrations.AlterField(
            model_name='compra',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
