# Generated by Django 5.2.13 on 2026-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_avaliacao_options_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('pending_refund', 'Reembolso Pendente'), ('completed', 'Concluído'), ('refunded', 'Reembolsado')], default='pending', max_length=30),
        ),
    ]
