# Generated by Django 5.2.13 on 2026-05-09 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_compra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='preco',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='media_avaliacoes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('usuario', 'curso')},
        ),
    ]
