# Generated by Django 4.2.16 on 2026-05-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_usuario_managers_alter_avaliacao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('refunded', 'Reembolsado')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='curso',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
