# Generated by Django 4.2.16 on 2026-05-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_avaliacao_comentario_alter_compra_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
