FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# dependências do sistema (para wait do DB)
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# dependências python
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# copia projeto
COPY . .

# garante permissão do entrypoint
RUN chmod +x docker/entrypoint.sh

# pasta do projeto Django
WORKDIR /app/software_sales

# inicia via entrypoint
ENTRYPOINT ["sh", "/app/docker/entrypoint.sh"]