FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

RUN chmod +x /app/docker/entrypoint.sh

WORKDIR /app/software_sales

ENTRYPOINT ["/app/docker/entrypoint.sh"]

CMD ["gunicorn", "software_sales.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]